FROM golang:1.22-bookworm AS build
WORKDIR /app
COPY go.mod ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app ./

FROM gcr.io/distroless/static-debian12:nonroot
WORKDIR /
COPY --from=build /app/app /app
USER nonroot:nonroot
EXPOSE 8081
CMD ["/app"]
